### ISSUE TITLE
docs: Are you accepting new contributors?

### ISSUE THREAD

**Issue by savionascimentodev** [vitejs/docs-pt#305]
Hello gentlemen, I'm a little new to the open source world, but I want to learn more and I want to contribute with you in this project, I've only been working with programming for over 3 years, and I want to be able to help, waiting for your response!

**Comment by nazarepiedady** [comment]
@savionascimentodev, I welcome you into this initiative.

I will create some issues on Monday to assign to you.

**Comment by nazarepiedady** [comment]
@savionascimentodev, I had some unwanted problems, so I will try to organise the things starting from tomorrow.

**Comment by savionascimentodev** [comment]
No problem @nazarepiedady.
